dataset_name: TCGA-KIRP
modalities:
  CT:
    folder: TCGA-KIRP/CT
    classes:
      early_stage: 0
      advanced_stage: 1
  MR:
    folder: TCGA-KIRP/MR
    classes:
      early_stage: 0
      advanced_stage: 1
  PT:
    folder: TCGA-KIRP/PT
    classes:
      early_stage: 0
      advanced_stage: 1
metadata:
  file: pipeline_metadata.csv
  split_column: split
  image_column: image_path
